version: 1.1.{build}
image: Visual Studio 2017
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - ExpressionToString/
    - Shared/
    - Visualizer.Shared
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
configuration: ReleaseCI
artifacts:
  - path: ExpressionToString\bin\Release\*.nupkg
    type: NuGetPackage

  - path: ExpressionTreeVisualizer.2017\bin\ReleaseCI\ExpressionTreeVisualizer.2017.dll
    type: File
    name: visualizer

  - path: ExpressionTreeVisualizer.2017\bin\ReleaseCI\*.pdb
    type: File
    name: visualizer

  - path: ExpressionTreeVisualizer.2017\bin\ReleaseCI\MultiSelectTreeView.dll
    type: File
    name: visualizer
deploy:
  - provider: NuGet
    api_key:
      secure: ggnvR8rEMLbVOYOAMBXmjD+ohPaPoCcMwwEPdQvMbpjt+HEHWFxZYNGXs+O1x8tD
    artifact: /.*\.nupkg/
  - provider: GitHub
    desciprion: ''
    auth_token:
      secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
    artifact: visualizer
matrix:
  fast_finish: true