version: 1.6.{build}
image: Visual Studio 2019
configuration: Debug
init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - Debuggee/
    - Package/
    - Serialization/
    - UI/
    - Visualizer/
    - Visualizer.Xaml/
    - appveyor.yml

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: dotnet restore

build:
  project: CI.sln

matrix:
  fast_finish: true

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\ExpressionTreeVisualizer.2017.zip %APPVEYOR_BUILD_FOLDER%\Visualizer\bin\Debug\net472\*
  - 7z a %APPVEYOR_BUILD_FOLDER%\ExpressionTreeVisualizer.2019.zip %APPVEYOR_BUILD_FOLDER%\Visualizer\bin\Debug\net472\*
  - cd %APPVEYOR_BUILD_FOLDER%\Debuggee\bin\Debug
  - 7z a %APPVEYOR_BUILD_FOLDER%\ExpressionTreeVisualizer.2019.zip -r *.dll

artifacts:
  - path: '%APPVEYOR_BUILD_FOLDER%\ExpressionTreeVisualizer.2019.zip'
    type: File
    name: visualizer

  - path: '%APPVEYOR_BUILD_FOLDER%\ExpressionTreeVisualizer.2017.zip'
    type: File
    name: visualizer

deploy:
  - provider: GitHub
    desciprion: ''
    auth_token:
      secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
    artifact: visualizer